[[entries]]
name = "APacCHRIE 2025"
full_name = "Asia Pacific Council on Hotel, Restaurant and Institutional Education Annual Conference"
host = "Chiang Mai University, Thailand"
type = "Oral"
year = "2025"
photos = ["/conference/APacCHRIE 2025.jpg"]

[[entries]]
name = "IMPACT 2025"
full_name = "International Conference on Innovation and Management"
host = "Hong Kong Polytechnic University"
type = "Oral"
year = "2025"
photos = ["/conference/IMPACT 2025.jpg"]

[[entries]]
name = "IPAS 2025"
full_name = "International Conference on Planetary Actions for Sustainability"
host = "University of Tokyo"
type = "Poster"
year = "2025"
photos = ["/conference/IPAS 2025.jpg"]

[[entries]]
name = "National Tourism Geography Annual Conference (全国旅游地理学年会)"
full_name = "2024 National Tourism Geography Annual Conference"
host = "Guangzhou, China"
type = "Oral"
year = "2024"
photos = ["/conference/2024年全国旅游地理学年会.jpg"]

[[entries]]
name = "National Human Geography Conference (全国人文地理学大会)"
full_name = "2023 National Human Geography Conference"
host = "Shaanxi Normal University"
type = "Oral"
year = "2023"
photos = ["/conference/2023全国人文地理学大会.jpg"]

[[entries]]
name = "Zhejiang Geographical Society Annual Conference (浙江省地理学会学术年会)"
full_name = "2022 Annual Academic Conference of Zhejiang Geographical Society"
host = "Zhejiang University"
type = "Oral"
year = "2022"
photos = ["/conference/浙江省地理学会2022年学术年会.jpg"]
