[[entries]]
name = "APacCHRIE 2025"
full_name = "Asia Pacific Council on Hotel, Restaurant and Institutional Education Annual Conference"
type = "Oral"
year = "2025"
photos = ["/conference/APacCHRIE 2025.jpg", "/conference/APacCHRIE 2025 -2.jpg"]

[[entries]]
name = "IMPACT 2025"
full_name = "International Conference on Innovation and Management in Applied Sciences and Computing Technologies"
type = "Oral"
year = "2025"
photos = ["/conference/IMPACT 2025.jpg"]

[[entries]]
name = "IPAS 2025"
full_name = "International Planning and Architecture Symposium"
type = "Poster"
year = "2025"
photos = ["/conference/IPAS 2025.jpg", "/conference/IPAS 2025 -2.jpg"]

[[entries]]
name = "National Human Geography Conference (全国人文地理学大会)"
full_name = "2023 National Human Geography Conference"
type = "Oral"
year = "2023"
photos = ["/conference/2023全国人文地理学大会.jpg"]

[[entries]]
name = "Zhejiang Geographical Society Annual Conference (浙江省地理学会学术年会)"
full_name = "2022 Annual Academic Conference of Zhejiang Geographical Society"
type = "Oral"
year = "2022"
photos = ["/conference/浙江省地理学会2022年学术年会.jpg"]
