[[entries]]
institution = "Zhejiang University"
logo = "/zju-logo.jpg"
degree = "Ph.D."
field = "Resources, Environment and Regional Planning"
department = "School of Earth Sciences"
start = "Sep. 2022"
end = "present"
gpa = "3.80 / 4.0"

[[entries]]
institution = "Zhejiang University"
logo = "/zju-logo.jpg"
degree = "B.S."
field = "Human Geography & Urban-Rural Planning"
department = "School of Earth Sciences"
start = "Sep. 2018"
end = "Jun. 2022"
gpa = "3.83 / 4.0"
